:Author: ard12sgf1960
:Email: {AuthorEmail}
:Date: 24/12/2022
:Revision: version#
:License: Public Domain

= Project: {Nano RP2040 Microphone}

Monitor the microphone and switch LEDs On and Off with a sound over a preset dB 

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Nano_RP2040_Microphone                => Arduino sketch folder
  ├── Nano_RP2040_Microphone.ino       => main Arduino file
  └── ReadMe.adoc                     => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ard12sgf1960 https://id.arduino.cc/ard12sgf1960

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| B1 | Nano RP2040    | Unknown     | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
